name: Python Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências do Python
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-dotenv pyspark pandas matplotlib seaborn jupyter

    - name: Executar os testes com Pytest
      run: |
        pytest
